### PR TITLE
Prepare 0.1.3 release

### PR DESCRIPTION
**Pull request by beck**

### CODE REVIEW

**Comment by zoidyzoidzoid** [comment]
:+1:

**Comment by beck** [comment]
:smiley:

**Comment by stefanor** [comment]
Hi @zoidbergwill :)

**Comment by zoidyzoidzoid** [comment]
@stefanor o/

**Comment by adrianmoisey** [comment]
Do you mind adding a tag for this release? https://github.com/yola/yolapy/releases

**Comment by beck** [comment]
My bad.  Tag added.

**Comment by adrianmoisey** [comment]
:star2:

**Pull request merged**
