### PR TITLE
Add site id argument to sso open site url

### PR DESCRIPTION
**Pull request by jslang**

### CODE REVIEW

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by jslang** [comment]
Looking into python 3.2 failure

**Comment by jslang** [comment]
Looks like failures are due to python3.2 incompatible changes in requests library. Should we peg requests to working version (latest 2.10.0) or drop support for 3.2? @yola/service-engineering

**Comment by highflyingaction** [comment]
Short term fix: add `requests==2.10.0` in `yolapy/requirements.txt`
Long term fix: drop Python 3.2 support.

I think dropping 3.2 would be best but it would be nice to know what percentage of partners are using it first.

**Comment by jslang** [comment]
Should be noted that python 3.2 is not officially supported by requests lib (edit: jk it was _officially_ supported until 2.10)

**Comment by jslang** [comment]
@yola/service-engineering 🔔

**Comment by thomasw** [comment]
I'm assuming people are waiting on the testing issue to be resolved?

**Comment by jslang** [comment]
> I'm assuming people are waiting on the testing issue to be resolved?

 Testing issue is what I need input on. Tests only fail on python 3.2, which is a result of newest version of requests lib not supporting 3.2. I can either peg requests to last working version (2.10) or we can drop support for python 3.2.

**Comment by thomasw** [comment]
Drop 3.2 support. There are other high profile libraries aside from just requests that have dropped support for it as well and we'll keep running into issues like this one.

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by stefanor** [comment]
:+1:

**Pull request merged**
