### PR TITLE
Update to version 0.1.6 with python 3 support

### PR DESCRIPTION
**Pull request by alexmojaki**
In relation to #35

### CODE REVIEW

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by RayeN** [comment]
I don't thin we should release these changes (since they don't change anything) - just put them to changelog (without version bump)?

**Comment by alexmojaki** [comment]
There is an actual change though. Python 3 didn't work before but now it does because of demands. And the behaviour of demands is probably slightly different too.

**Comment by RayeN** [comment]
The only change here, was to make tests passing for python 3 (demands version was upgraded only for tests). That makes me thinking that I probably missed your intension in your previous pull. So, don't think we should even mention that in changelog - or otherwise we should increase minor required `demands` version in `setup.py` (installation requirements).

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by alexmojaki** [comment]
Ah, I'd forgotten how `requirements.txt` is used.

**Comment by RayeN** [comment]
:+1:

**Pull request merged**
