### PR TITLE
Allow six < 2.0.0

### PR DESCRIPTION
**Pull request by kosmos342**

### CODE REVIEW

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by kosmos342** [comment]
I don't know how much data can be passed to `SiteImport.__init__` and `Site.__init__` https://github.com/yola/yolapy/blob/2f5cc1c66cf4d2a33c4c3aa820af27133dd9890a/yolapy/models/siteimport.py#L7-L12 https://github.com/yola/yolapy/blob/79c6e6eb4430b16ccbfedc274b06555190314694/yolapy/models/site.py#L8-L14 but maybe we can use `kwargs.items()` and remove `six` dependency completely

**Review by stefanor — APPROVED** [review]
Yep, I think that requirement was too strict before.

**Comment by kosmos342** [comment]
@stefanor what do you think to use `kwargs.items()` and remove six dependency completely?

**Comment by stefanor** [comment]
I don't know the quantity either, but that would work...

**Comment by kosmos342** [comment]
I don't think that quantitiy of kwargs will be a lot, anyway we do not process them on the fly, but save them in fields

**Comment by kosmos342** [comment]
There will be another changes, so I'll remove six in another PR

**Comment by kosmos342** [comment]
`six` was removed in another PR

**Pull request closed without merging**
