### PR TITLE
bump version to 0.2.3

### PR DESCRIPTION
**Pull request by highflyingaction**
New addition doesn't break anything so I went to 0.2.3.

### CODE REVIEW

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by thomasw** [comment]
I'd go with a minor since you added functionality.

Seriously though, screw that. 1.0.0.

**Comment by highflyingaction** [comment]
I don't know about 1.0.0. Seems like there's quite a bit it doesn't do yet.
@blaix, weigh in.
Do version numbers still have meaning in our modern world?

**Comment by blaix** [comment]
> I'd go with a minor since you added functionality.

What @jamesodo did follows the pattern we've been following for 0.x where we treat minor as the breaking version.

> Seriously though, screw that. 1.0.0.

There are not models for all resources, and the models we do have don't have all their lifecycle methods in them. And this isn't being used in production anywhere yet, and we haven't officially made it a public example of consuming our API yet, so I don't think we're ready to say this is our stable, 1.0 client.

_But_ I don't feel very strongly about it. If others want it 1.0, I'm fine with that. 👍 otherwise.

**Pull request merged**
